"""initial schema

Revision ID: c03529f04896
Revises: 
Create Date: 2026-07-27 16:48:32.061771
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'c03529f04896'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_handle'), ['handle'], unique=True)

    op.create_table('skill',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prerequisite_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_code'), ['code'], unique=True)

    op.create_table('task',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('notation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_ids', sa.JSON(), nullable=True),
    sa.Column('difficulty_b', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_task_id'), ['task_id'], unique=False)

    op.create_table('claim',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_unassisted', sa.Integer(), nullable=False),
    sa.Column('n_assisted', sa.Integer(), nullable=False),
    sa.Column('last_evidence_attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_evidence_at', sa.DateTime(), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_task_ids', sa.JSON(), nullable=True),
    sa.Column('evidence_attempt_ids', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'skill_id', name='uq_claim_learner_skill')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_skill_id'), ['skill_id'], unique=False)

    op.create_table('diagnosis',
    sa.Column('attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_break_index', sa.Integer(), nullable=True),
    sa.Column('error_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('misconception_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('probe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('step',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formalised', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formaliser_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('verification',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_step_id'), ['step_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_step_id'))

    op.drop_table('verification')
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_attempt_id'))

    op.drop_table('step')
    op.drop_table('diagnosis')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_skill_id'))
        batch_op.drop_index(batch_op.f('ix_claim_learner_id'))

    op.drop_table('claim')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_task_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_learner_id'))

    op.drop_table('attempt')
    op.drop_table('task')
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_code'))

    op.drop_table('skill')
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_handle'))

    op.drop_table('learner')
    # ### end Alembic commands ###
